mytable2$p16.promoter<-"no_p16_promoter"
mytable2$p16.promoter[filtered_rows]<-"p16_promoter"
mytable2$p16.norm <- mytable2$p16.dialup/mytable2$crop_nUMI
mytable2$p14.norm <- mytable2$p14.dialup/mytable2$crop_nUMI

ggplot(mytable2[mytable2$orig.ident=="mRNA_array1",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 1 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array1",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 1 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array2",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 2 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array2",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 2 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array3",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 3 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array3",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 3 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array4",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 4 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array4",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 4 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array5",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 5 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array5",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 5 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array6",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 6 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array6",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 6 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array7",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 7 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array7",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 7 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array8",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 8 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array8",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 8 p14 dialup p16 promoter guide", y = "p14 dialup")

ggplot(mytable2[mytable2$orig.ident=="mRNA_array9",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 9 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array9",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 9 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array10",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 10 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array10",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 10 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array11",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 11 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array11",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 11 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array12",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 12 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array12",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 12 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array13",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 13 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array13",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 13 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array14",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 14 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array14",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 14 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array15",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 15 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array15",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 15 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array16",], aes(x=p16.promoter, y=p16.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 16 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array16",], aes(x=p16.promoter, y=p14.dialup, fill = p16.promoter)) + geom_violin() + labs(title = "Array 16 p14 dialup p16 promoter guide", y = "p14 dialup")


ggplot(mytable2[mytable2$orig.ident=="mRNA_array1",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 1 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array1",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 1 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array2",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 2 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array2",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 2 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array3",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 3 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array3",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 3 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array4",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 4 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array4",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 4 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array5",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 5 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array5",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 5 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array6",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 6 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array6",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 6 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array7",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 7 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array7",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 7 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array8",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 8 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array8",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 8 p14 dialup p16 promoter guide", y = "p14 dialup")

ggplot(mytable2[mytable2$orig.ident=="mRNA_array9",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 9 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array9",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 9 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array10",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 10 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array10",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 10 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array11",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 11 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array11",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 11 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array12",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 12 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array12",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 12 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array13",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 13 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array13",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 13 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array14",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 14 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array14",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 14 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array15",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 15 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array15",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 15 p14 dialup p16 promoter guide", y = "p14 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array16",], aes(x=p16.promoter, y=p16.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 16 p16 dialup p16 promoter guide", y = "p16 dialup")
ggplot(mytable2[mytable2$orig.ident=="mRNA_array16",], aes(x=p16.promoter, y=p14.norm, fill = p16.promoter)) + geom_violin() + labs(title = "Array 16 p14 dialup p16 promoter guide", y = "p14 dialup")


p1 <- ggplot(filtered_data2, aes(x = p14.dialup, y = sgRNA_21994286.21994909_21994555_gene)) + geom_point() + labs(title = "p14 dialup vs guide1", x = "p14 dialup", y = "cut site 21994555")
p2 <- ggplot(filtered_data2, aes(x = p14.dialup, y = sgRNA_21994286.21994909_21994611_gene)) + geom_point() + labs(title = "p14 dialup vs guide2", x = "p14 dialup", y = "cut site 21994611")
p3 <- ggplot(filtered_data2, aes(x = p14.dialup, y = sgRNA_21994286.21994909_21994745_gene)) + geom_point() + labs(title = "p14 dialup vs guide3", x = "p14 dialup", y = "cut site 21994745")
p4 <- ggplot(filtered_data2, aes(x = p14.dialup, y = sgRNA_21994286.21994909_21994907_gene)) + geom_point() + labs(title = "p14 dialup vs guide4", x="p14 dialup", y = "cut site 21994907")
gridExtra::grid.arrange(p1, p2, p3, p4, nrow = 2)


